# window is required
[window]
width = 800
height = 800

# pipeline is required
[[pipeline]]
shader_type = "fragment"
label = "fragment_shader"
entry_point = "fs_main"
#file = "0_0_helloWorld.wgsl"
#file = "0_1_helloWorld.wgsl"
#file = "1_0_lerp.wgsl"
#file = "1_1_lerpTriple.wgsl"
#file = "1_2_bilerp.wgsl"
file = "1_3_posterization.wgsl"
